// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "Door Closed":return img`
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bfffbeeeeeebfffb
bfffbeeeeeebfffb
bffffeeeeeeffffb
bfffbeeeeeebfffb
bfffbeeeeeebfffb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
bbbbbeeeeeebbbbb
`;
            case "image5":
            case "Door Open":return img`
................................
.eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
.eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
.eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
.eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
.eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
..............bfbbbbbbbbbbbbbbb.
............bbbfbbbbbbbbbbbbbbb.
............bfffffbbbbbbbbbbbbb.
............bfffffbbbbbbbbbbbbb.
............bbbbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
..............bbbbbbbbbbbbbbbbb.
................................
`;
            case "image8":
            case "Cat":return img`
. . . . . . . . . . . . . . 
e e e . . . . e e e . . . . 
c d d c . . c d d c . . . . 
c b d d f f d d b c . . . . 
c 3 b d d b d b 3 c . . . . 
f b 3 d d d d 3 b f . . . . 
e d d d d d d d d e . . . . 
e d f d d d d f d e b f b . 
f d d f d d f d d f f d f . 
f b d d b b d d 2 b f d f . 
. f 2 2 2 2 2 2 d b d b f . 
. f d d d d d d d f f f . . 
. f d b d f f f d f . . . . 
. . f f f f . . f f . . . . 
`;
            case "Uqgd3bm/Q+SEc+0hQ8Sn":
            case "Dog":return img`
. . . . . . . . . . . . . . . . 
. . . . . . 4 4 4 4 . . . . . . 
. . . . 4 4 4 5 5 4 4 4 . . . . 
. . . 3 3 3 3 4 4 4 4 4 4 . . . 
. . 4 3 3 3 3 2 2 2 1 1 4 4 . . 
. . 3 3 3 3 3 2 2 2 1 1 5 4 . . 
. 4 3 3 3 3 2 2 2 2 2 5 5 4 4 . 
. 4 3 3 3 2 2 2 4 4 4 4 5 4 4 . 
. 4 4 3 3 2 2 4 4 4 4 4 4 4 4 . 
. 4 2 3 3 2 2 4 4 4 4 4 4 4 4 . 
. . 4 2 3 3 2 4 4 4 4 4 2 4 . . 
. . 4 2 2 3 2 2 4 4 4 2 4 4 . . 
. . . 4 2 2 2 2 2 2 2 2 4 . . . 
. . . . 4 4 2 2 2 2 4 4 . . . . 
. . . . . . 4 4 4 4 . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "4I:wR!r8iVt/n)":
            case "Skull":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.....3.
......fffcdb1bdffff...3.
....fc111cbfbfc111cf..3.
....f1b1b1ffff1b1b1f.33.
....fbfbffffffbfbfbf.33.
.........ffffff.....3333
...........fff......3333
...................33333
...................33333
...................333..
....................333.
`;
            case "image2":
            case "Monkey":return img`
. . . . f f f f f . . . . . . . 
. . . f e e e e e f . . . . . . 
. . f d d d d e e e f . . . . . 
. c d f d d f d e e f . . . . . 
. c d f d d f d e e f f . . . . 
c d e e d d d d e e d d f . . . 
c d d d d c d d e e b d c . . . 
c c c c c d d e e e b d c . f f 
. f d d d d e e e f f c . f e f 
. f f f f f f e e e e f . f e f 
. f f f f e e e e e e e f f e f 
f d d f d d f e f e e e e f f . 
f d b f d b f e f e e e e f . . 
f f f f f f f f f f f f e f . . 
. . . . . . . . . f c d d f . . 
. . . . . . . . . . f f f f . . 
`;
            case "image9":
            case "Bob_Has_Key30":return img`
8 8 8 8 8 8 8 8 
8 5 5 5 5 5 5 8 
8 5 5 5 5 5 5 8 
8 5 5 2 2 5 5 8 
8 5 5 2 2 5 5 8 
8 5 5 5 5 5 5 8 
8 5 5 5 5 5 5 8 
8 8 8 8 8 8 8 8 
`;
            case "image6":
            case "Key-12":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. 4 4 4 4 4 . . . . . . . . . . 
. 4 5 5 5 4 . . 4 4 4 . 4 4 4 . 
. 4 5 f 5 4 . . 4 5 4 4 4 5 4 . 
. 4 5 f 5 4 4 4 4 5 4 5 4 5 4 . 
. 4 5 f 5 5 5 5 5 5 5 5 5 5 4 . 
. 4 5 f 5 4 4 4 4 4 4 4 4 4 4 . 
. 4 5 5 5 4 . . . . . . . . . . 
. 4 4 4 4 4 . 8 . 8 8 8 8 . . . 
. . . . . . . 8 . . . . 8 . . . 
. . . . . . . 8 . . . 8 8 . . . 
. . . . . . . 8 . . 8 8 . . . . 
. . . . . . . 8 . 8 8 . . . . . 
. . . . . . . 8 . 8 8 8 8 . . . 
`;
            case "image7":
            case "Bob_Has_Key":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f 4 4 f f . . . . . 
. . . . f 5 4 5 5 4 5 f . . . . 
. . . f e 3 3 3 3 3 3 e f . . . 
. . f b 3 3 3 3 3 3 3 3 b f . . 
. . f 3 3 3 3 3 3 3 3 3 3 f . . 
. f b 3 3 3 3 3 3 3 3 3 3 b f . 
. f b b 3 3 3 3 3 3 3 3 b b f . 
. f b b b b b b b b b b b b f . 
f c b b b b b b b b b b b b f . 
f b b b b b b b b b b b b c f . 
f f b b b b b b b b b b c f . . 
. f c c c f f f f f f f e c . . 
. . . f b b d b d d e 4 4 e . . 
. . . f f 1 1 d 1 d e e f . . . 
. . . . . f b b f f f . . . . . 
`;
            case "image10":
            case "Key_0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. 4 4 4 4 4 . . . . . . . . . . 
. 4 5 5 5 4 . . 4 4 4 . 4 4 4 . 
. 4 5 f 5 4 . . 4 5 4 4 4 5 4 . 
. 4 5 f 5 4 4 4 4 5 4 5 4 5 4 . 
. 4 5 f 5 5 5 5 5 5 5 5 5 5 4 . 
. 4 5 f 5 4 4 4 4 4 4 4 4 4 4 . 
. 4 5 5 5 4 . . . . . . . . . . 
. 4 4 4 4 4 . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "BobWithKey":return img`
5 5 5 5 5 5 f f f f 5 5 5 5 5 5 
5 5 5 5 f f f 2 2 f f f 5 5 5 5 
5 5 5 f f f 2 2 2 2 f f f 5 5 5 
5 5 f f f e e e e e e f f f 5 5 
5 5 f f e 2 2 2 2 2 2 e e f 5 5 
5 5 f e 2 f f f f f f 2 e f 5 5 
5 5 f f f f e e e e f f f f 5 5 
5 f f e f b f 4 4 f b f e f f 5 
5 f e e 4 1 f d d f 1 4 e e f 5 
5 5 f e e d d d d d d e e f 5 5 
5 5 5 f e e 4 4 4 4 e e f 5 5 5 
5 5 e 4 f 2 2 2 2 2 2 f 4 e 5 5 
5 5 4 d f 2 2 2 2 2 2 f d 4 5 5 
5 5 4 4 f 4 4 5 5 4 4 f 4 4 5 5 
5 5 5 5 5 f f f f f f 5 5 5 5 5 
5 5 5 5 5 f f 5 5 f f 5 5 5 5 5 
`;
            case "image11":
            case "Bob0":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image1":
            case "X-Y Target":return img`
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . f f f f . . . . . 2 
2 . . . . . f 2 2 f . . . . . 2 
2 . . . . . f 2 2 f . . . . . 2 
2 . . . . . f f f f . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 . . . . . . . . . . . . . . 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
`;
            case "image13":
            case "BobSward02":return img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`;
            case "image14":
            case "BobSward03":return img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image15":
            case "BobSward00":return img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image16":
            case "BobSward0":return img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
`;
            case "image12":
            case "BobSward01":return img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
................33......
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
